teleop_twist_joy_node:
  ros__parameters:
    arm_axis_linear:  # Left thumb stick vertical
      x: 1
      y: 0
      z: 4
    arm_scale_linear:
      x: 0.7
      y: -0.7
      z: 0.7
    arm_axis_angular:  # Left thumb stick horizontal
      yaw: 3
      pitch: 1
      roll: 0
    arm_scale_angular:
      yaw: -0.4
      pitch: 0.4
      roll: -0.4
    arm_gripper: 
      close: 2 # Left trigger
      open: 5 # Right trigger
    arm_pose_preset_button:
      home: 1 # "B" Button
      retract: 0 # "A" Button
    arm_toggleCartAdmittance: 2 # "X" Button
    arm_toggleNullAdmittance: 3 # "Y" Button
    arm_pose_presets:
      home:
        x: 1.0
        y: 0.0
        z: 0.0
        yaw: 0.0
        pitch: 0.0
        roll: 0.0
      retract:
        x: 0.0
        y: 0.0
        z: 0.0
        yaw: 0.0
        pitch: 0.0
        roll: 0.0
      twist_door_handle:
      
    base_axis_linear:  # Left thumb stick vertical
      x: 1
    base_scale_linear:
      x: 0.7
    base_axis_angular:  # Left thumb stick horizontal
      yaw: 3
    base_scale_angular:
      yaw: -0.4
    
    XYTwist_toggle: 8 # Left joystick button to switch between controlling translation and rotation in the X and Y axes
    ZTwist_toggle: 9 # Right joystick button to switch between controlling translation and rotation in the Z axes
      
    jog_arm_button: 10  # X button. Button idex start from 1 for some reason.
    deactivate_estop_button: 4  # Left bumper button
    activate_estop_button: 5  # Right bumper button
